-- PostgreSQL schema for NOVA backend
-- Safe to run multiple times

CREATE EXTENSION IF NOT EXISTS citext;

-- =========================
-- USERS
-- =========================
CREATE TABLE IF NOT EXISTS users (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name       TEXT,
  last_name        TEXT,
  username         CITEXT NOT NULL,
  email            CITEXT NOT NULL,
  password         TEXT,
  phone            TEXT,
  dob              DATE,
  gender           TEXT,
  google_id        TEXT,
  accepted_terms   BOOLEAN NOT NULL DEFAULT FALSE,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login       TIMESTAMPTZ,
  role             TEXT,
  place_id         BIGINT,
  token_version    INTEGER NOT NULL DEFAULT 1,

  CONSTRAINT uq_users_username UNIQUE (username),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT uq_users_google_id UNIQUE (google_id),
  CONSTRAINT chk_users_token_version CHECK (token_version >= 1),
  CONSTRAINT chk_users_role CHECK (
    role IN ('admin_general', 'user_general', 'user_place') OR role IS NULL
  )
);

-- =========================
-- PLACES
-- =========================
CREATE TABLE IF NOT EXISTS places (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT NOT NULL,
  tipo                TEXT NOT NULL,
  lugar               TEXT NOT NULL,
  description         TEXT NOT NULL,
  image_url           TEXT,
  rating              NUMERIC(3,2) NOT NULL DEFAULT 0,
  address             TEXT,
  phone               TEXT,
  price_range         TEXT,
  amenities           JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_active           BOOLEAN NOT NULL DEFAULT TRUE,
  has_reward          BOOLEAN NOT NULL DEFAULT FALSE,
  reward_name         TEXT,
  reward_description  TEXT,
  reward_icon         TEXT DEFAULT '🎁',
  reward_stock        INTEGER,
  owner_id            BIGINT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT chk_places_tipo CHECK (tipo IN ('hotel', 'restaurant', 'bar')),
  CONSTRAINT chk_places_rating CHECK (rating >= 0 AND rating <= 5),
  CONSTRAINT chk_places_stock CHECK (reward_stock IS NULL OR reward_stock >= 0)
);

-- =========================
-- FOREIGN KEYS (SAFE)
-- =========================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_place'
  ) THEN
    ALTER TABLE users
    ADD CONSTRAINT fk_users_place
    FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE SET NULL;
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_places_owner'
  ) THEN
    ALTER TABLE places
    ADD CONSTRAINT fk_places_owner
    FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END$$;

-- =========================
-- SCANS
-- =========================
CREATE TABLE IF NOT EXISTS scans (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  place_id    BIGINT NOT NULL,
  qr_code     TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_scans_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_scans_place FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE CASCADE
);

-- =========================
-- REWARDS
-- =========================
CREATE TABLE IF NOT EXISTS rewards (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             BIGINT NOT NULL,
  place_id            BIGINT NOT NULL,
  reward_name         TEXT NOT NULL,
  reward_description  TEXT,
  reward_icon         TEXT DEFAULT '🎁',
  is_redeemed         BOOLEAN NOT NULL DEFAULT FALSE,
  earned_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  redeemed_at         TIMESTAMPTZ,

  CONSTRAINT fk_rewards_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_rewards_place FOREIGN KEY (place_id) REFERENCES places(id) ON DELETE CASCADE
);

-- =========================
-- SESSIONS (AUTH V2)
-- =========================
CREATE TABLE IF NOT EXISTS sessions (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             BIGINT NOT NULL,
  refresh_token_hash  TEXT NOT NULL,
  user_agent          TEXT,
  ip                  INET,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at          TIMESTAMPTZ NOT NULL,
  revoked             BOOLEAN NOT NULL DEFAULT FALSE,
  replaced_by_token   TEXT,

  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT chk_sessions_expires CHECK (expires_at > created_at)
);

-- =========================
-- COMMENT
-- =========================
COMMENT ON COLUMN sessions.id IS 'Session identifier. JWT v2 claim sid must match this id.';